import { defineConfig } from "vitest/config";
import base from "./vitest.config.mts";

export default defineConfig({
  ...base,
  test: {
    ...base.test,
    include: [
      "test/auth-consent.spec.ts",
      "test/code-mode-custom-mcp.spec.ts",
      "test/custom-mcp-authority-policy.spec.ts",
      "test/custom-mcp-contract.spec.ts",
      "test/d1-capability-kernel.spec.ts",
      "test/d1-custom-mcp-activation-fence.spec.ts",
      "test/d1-custom-mcp-dispatcher.spec.ts",
      "test/deployment-api.spec.ts",
      "test/deployment-status-api.spec.ts",
      "test/cloudflare-oauth-api.spec.ts",
      "test/d1-cloudflare-revocation-index.spec.ts",
      "test/d1-deployment-repository.spec.ts",
      "test/d1-temporary-operation-recovery.spec.ts",
      "test/deployment-orchestration.spec.ts",
      "test/cloudflare-revocation-reconciler.spec.ts",
      "test/cloudflare-temporary-readiness.spec.ts",
      "test/cloudflare-support-health.spec.ts",
      "test/customer-static-runtime-gate.spec.ts",
      "test/support-service-attestation.spec.ts",
      "test/support-service-attestation-api.spec.ts",
      "test/managed-platform-reservation-api.spec.ts",
      "test/managed-deployment-broker.spec.ts",
      "test/managed-runtime-kernel.spec.ts",
      "test/managed-runtime-gateway-contract.spec.ts",
      "test/managed-runtime-state.spec.ts",
      "test/temporary-claim-api.spec.ts",
      "test/temporary-claim-delivery-recovery.spec.ts",
      "test/temporary-operation-reconciler.spec.ts",
      "test/cloudflare-support-services.spec.ts",
      "test/revision-deployment-coordinator.spec.ts",
      "test/trusted-review-confirmation-api.spec.ts",
      "test/kernel-admin-audit.spec.ts",
      "test/kernel-document-security.spec.ts",
      "test/custom-workflow-api.spec.ts",
      "test/cli.spec.ts",
      "test/cli-browser-session-api.spec.ts",
      "test/review-session-recovery.spec.ts",
      "test/revision-api.spec.ts",
      "test/security-model.spec.ts",
      "test/shiplet-package.spec.ts",
      "test/trusted-artifact-bridge.spec.ts",
      "test/trusted-review-host.spec.ts",
      "test/timing-safe-secret.spec.ts",
      "test/wordpress-embed.spec.ts",
      "test/workos-invitation-security.spec.ts",
    ],
  },
});
