import { cloudflareTest } from "@cloudflare/vitest-pool-workers";
import { defineConfig } from "vitest/config";

export default defineConfig({
  envDir: false,
  plugins: [
    cloudflareTest({
      wrangler: { configPath: "./wrangler.test.jsonc" },
      remoteBindings: false,
      miniflare: {
        d1Databases: ["DB"],
        r2Buckets: ["SHIPLET_ASSETS", "REVIEW_ASSETS"],
        bindings: {
          SHIPLET_AUTH_MODE: "test",
          DISPATCH_NAMESPACE_NAME: "test-namespace",
          CUSTOM_DOMAIN: "",
          ACCOUNT_ID: "test-account-id",
          DISPATCH_NAMESPACE_API_TOKEN: "test-api-token",
          SHIPLET_BOOTSTRAP_TOKEN: "test-bootstrap-token",
        },
      },
    }),
  ],
  test: {
    include: [
      "test/auth-consent.spec.ts",
      "test/code-mode-custom-mcp.spec.ts",
      "test/custom-mcp-authority-policy.spec.ts",
      "test/custom-mcp-contract.spec.ts",
      "test/d1-capability-kernel.spec.ts",
      "test/d1-custom-mcp-activation-fence.spec.ts",
      "test/d1-custom-mcp-dispatcher.spec.ts",
      "test/deployment-api.spec.ts",
      "test/deployment-status-api.spec.ts",
      "test/cloudflare-oauth-api.spec.ts",
      "test/d1-cloudflare-revocation-index.spec.ts",
      "test/d1-deployment-repository.spec.ts",
      "test/d1-temporary-operation-recovery.spec.ts",
      "test/deployment-orchestration.spec.ts",
      "test/cloudflare-revocation-reconciler.spec.ts",
      "test/cloudflare-temporary-readiness.spec.ts",
      "test/cloudflare-support-health.spec.ts",
      "test/customer-static-runtime-gate.spec.ts",
      "test/support-service-attestation.spec.ts",
      "test/support-service-attestation-api.spec.ts",
      "test/managed-platform-reservation-api.spec.ts",
      "test/managed-deployment-broker.spec.ts",
      "test/managed-runtime-kernel.spec.ts",
      "test/managed-runtime-gateway-contract.spec.ts",
      "test/managed-runtime-state.spec.ts",
      "test/temporary-claim-api.spec.ts",
      "test/temporary-effect-fence.spec.ts",
      "test/temporary-claim-delivery-recovery.spec.ts",
      "test/temporary-operation-reconciler.spec.ts",
      "test/cloudflare-support-services.spec.ts",
      "test/revision-deployment-coordinator.spec.ts",
      "test/trusted-review-confirmation-api.spec.ts",
      "test/kernel-admin-audit.spec.ts",
      "test/kernel-document-security.spec.ts",
      "test/custom-workflow-api.spec.ts",
      "test/cli.spec.ts",
      "test/cli-browser-session-api.spec.ts",
      "test/review-session-recovery.spec.ts",
      "test/revision-api.spec.ts",
      "test/security-model.spec.ts",
      "test/shiplet-package.spec.ts",
      "test/trusted-artifact-bridge.spec.ts",
      "test/trusted-review-host.spec.ts",
      "test/timing-safe-secret.spec.ts",
      "test/wordpress-embed.spec.ts",
      "test/workos-invitation-security.spec.ts",
    ],
  },
});
