// Generated by scripts/build-plugin-app.mjs.
// Do not edit by hand.

export const PLUGIN_APP_HTML = "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>Shiplet</title></head><body></body></html>";
