export const STATIC_IMAGE_EXTENSIONS = new Set([
	"avif",
	"bmp",
	"gif",
	"ico",
	"jfif",
	"jpeg",
	"jpg",
	"png",
	"svg",
	"webp",
]);

export const STATIC_VIDEO_EXTENSIONS = new Set([
	"3gp",
	"m4v",
	"mov",
	"mp4",
	"mpeg",
	"mpg",
	"ogv",
	"webm",
]);

export const STATIC_AUDIO_EXTENSIONS = new Set([
	"aac",
	"aif",
	"aiff",
	"flac",
	"m4a",
	"mid",
	"midi",
	"mp3",
	"oga",
	"ogg",
	"opus",
	"wav",
	"weba",
]);

export const STATIC_TEXT_EXTENSIONS = new Set([
	"asc",
	"astro",
	"bash",
	"bat",
	"bib",
	"c",
	"cc",
	"cfg",
	"cgi",
	"cjs",
	"clj",
	"cljs",
	"cljc",
	"cmd",
	"conf",
	"cpp",
	"cpg",
	"cs",
	"css",
	"csv",
	"cxx",
	"dart",
	"dbml",
	"dockerignore",
	"edn",
	"erl",
	"ex",
	"exs",
	"fish",
	"fs",
	"fsx",
	"geojson",
	"gitattributes",
	"gitignore",
	"gml",
	"go",
	"gpx",
	"gql",
	"gradle",
	"graphql",
	"groovy",
	"h",
	"hpp",
	"hrl",
	"htm",
	"html",
	"ini",
	"ipynb",
	"java",
	"jgw",
	"js",
	"json",
	"jsonc",
	"jsonl",
	"jsx",
	"kml",
	"kt",
	"kts",
	"log",
	"lua",
	"map",
	"md",
	"mdx",
	"mjs",
	"ml",
	"mli",
	"ndjson",
	"nim",
	"osm",
	"php",
	"pl",
	"pm",
	"pgw",
	"prj",
	"properties",
	"proto",
	"ps1",
	"py",
	"pyi",
	"qmd",
	"qpj",
	"r",
	"rb",
	"rs",
	"scala",
	"scss",
	"sh",
	"sld",
	"sol",
	"sql",
	"svelte",
	"swift",
	"tex",
	"tfw",
	"toml",
	"topojson",
	"ts",
	"tsv",
	"tsx",
	"txt",
	"vb",
	"vbs",
	"vue",
	"vrt",
	"webmanifest",
	"wkt",
	"wld",
	"xml",
	"yaml",
	"yml",
	"zig",
	"zsh",
]);

export const STATIC_ASSET_CONTENT_TYPES: Record<string, string> = {
	"3gp": "video/3gpp",
	"7z": "application/x-7z-compressed",
	aac: "audio/aac",
	aif: "audio/aiff",
	aiff: "audio/aiff",
	arrow: "application/vnd.apache.arrow.file",
	avi: "video/x-msvideo",
	avif: "image/avif",
	bmp: "image/bmp",
	bz2: "application/x-bzip2",
	cpg: "text/plain; charset=utf-8",
	css: "text/css; charset=utf-8",
	csv: "text/csv; charset=utf-8",
	dbf: "application/vnd.dbf",
	doc: "application/msword",
	docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	e57: "application/vnd.astm-e57",
	epub: "application/epub+zip",
	feather: "application/vnd.apache.arrow.file",
	fgb: "application/flatgeobuf",
	flac: "audio/flac",
	geojson: "application/geo+json; charset=utf-8",
	gif: "image/gif",
	gml: "application/gml+xml; charset=utf-8",
	gpkg: "application/geopackage+sqlite3",
	gpx: "application/gpx+xml; charset=utf-8",
	grb: "application/x-grib",
	grib: "application/x-grib",
	grib2: "application/x-grib",
	gz: "application/gzip",
	h5: "application/x-hdf5",
	hdf: "application/x-hdf",
	hdf5: "application/x-hdf5",
	heic: "image/heic",
	heif: "image/heif",
	htm: "text/html; charset=utf-8",
	html: "text/html; charset=utf-8",
	ico: "image/x-icon",
	ipynb: "application/json; charset=utf-8",
	js: "application/javascript; charset=utf-8",
	jfif: "image/jpeg",
	jpeg: "image/jpeg",
	jpg: "image/jpeg",
	json: "application/json; charset=utf-8",
	jsonc: "application/json; charset=utf-8",
	jsonl: "application/x-ndjson; charset=utf-8",
	kml: "application/vnd.google-earth.kml+xml; charset=utf-8",
	kmz: "application/vnd.google-earth.kmz",
	las: "application/vnd.las",
	laz: "application/vnd.laszip",
	m4a: "audio/mp4",
	m4v: "video/x-m4v",
	map: "application/json; charset=utf-8",
	mbtiles: "application/vnd.sqlite3",
	md: "text/markdown; charset=utf-8",
	mdx: "text/markdown; charset=utf-8",
	mid: "audio/midi",
	midi: "audio/midi",
	mjs: "application/javascript; charset=utf-8",
	mkv: "video/x-matroska",
	mov: "video/quicktime",
	mp3: "audio/mpeg",
	mp4: "video/mp4",
	mpeg: "video/mpeg",
	mpg: "video/mpeg",
	nc: "application/x-netcdf",
	ndjson: "application/x-ndjson; charset=utf-8",
	ods: "application/vnd.oasis.opendocument.spreadsheet",
	odt: "application/vnd.oasis.opendocument.text",
	oga: "audio/ogg",
	ogg: "audio/ogg",
	ogv: "video/ogg",
	opus: "audio/ogg",
	osm: "application/xml; charset=utf-8",
	otf: "font/otf",
	parquet: "application/vnd.apache.parquet",
	pcd: "application/octet-stream",
	pdf: "application/pdf",
	pmtiles: "application/vnd.pmtiles",
	png: "image/png",
	ppt: "application/vnd.ms-powerpoint",
	pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	prj: "text/plain; charset=utf-8",
	qgs: "application/xml; charset=utf-8",
	qgz: "application/zip",
	qix: "application/octet-stream",
	rtf: "application/rtf",
	sbn: "application/octet-stream",
	sbx: "application/octet-stream",
	shp: "application/vnd.shp",
	shx: "application/vnd.shx",
	sld: "application/xml; charset=utf-8",
	sqlite: "application/vnd.sqlite3",
	svg: "image/svg+xml",
	tar: "application/x-tar",
	tgz: "application/gzip",
	tif: "image/tiff",
	tiff: "image/tiff",
	topojson: "application/json; charset=utf-8",
	tsv: "text/tab-separated-values; charset=utf-8",
	ttf: "font/ttf",
	txt: "text/plain; charset=utf-8",
	webm: "video/webm",
	weba: "audio/webm",
	webmanifest: "application/manifest+json; charset=utf-8",
	webp: "image/webp",
	wav: "audio/wav",
	woff: "font/woff",
	woff2: "font/woff2",
	xls: "application/vnd.ms-excel",
	xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	xlsm: "application/vnd.ms-excel.sheet.macroEnabled.12",
	xml: "application/xml; charset=utf-8",
	zip: "application/zip",
};

for (const extension of STATIC_TEXT_EXTENSIONS) {
	STATIC_ASSET_CONTENT_TYPES[extension] ??= "text/plain; charset=utf-8";
}

export const ALLOWED_STATIC_ASSET_EXTENSIONS = new Set([
	...Object.keys(STATIC_ASSET_CONTENT_TYPES),
]);

export const ALLOWED_STATIC_ASSET_FILENAMES = new Set([
	".dockerignore",
	".eslintignore",
	".gitattributes",
	".gitignore",
	".prettierignore",
	"changelog",
	"dockerfile",
	"gemfile",
	"license",
	"makefile",
	"procfile",
	"rakefile",
	"readme",
]);

export const ALLOWED_STATIC_ASSET_DOTFILES = new Set(
	[...ALLOWED_STATIC_ASSET_FILENAMES].filter((name) => name.startsWith(".")),
);

export const BLOCKED_STATIC_ASSET_EXTENSIONS = new Set([
	"apk",
	"app",
	"bin",
	"class",
	"com",
	"deb",
	"dll",
	"dmg",
	"exe",
	"ipa",
	"jar",
	"msi",
	"pkg",
	"rpm",
]);

export function staticAssetExtension(path: string) {
	return path.split("/").pop()?.split(".").pop()?.toLowerCase() || "";
}

export function staticAssetFileName(path: string) {
	return path.split("/").pop()?.toLowerCase() || "";
}

export function staticAssetContentTypeForPath(path: string) {
	const extension = staticAssetExtension(path);
	return (
		STATIC_ASSET_CONTENT_TYPES[extension] ||
		(ALLOWED_STATIC_ASSET_FILENAMES.has(staticAssetFileName(path))
			? "text/plain; charset=utf-8"
			: "application/octet-stream")
	);
}
